name: FrostCases
version: 1.0
main: pro.frostworld.frostcases.FrostCases
api-version: 1.16
commands:
  frostcases:
    description: Управление блоками кейсов и открытие меню
    permission: frostcases.use
  frostworld:
    description: Системная команда управления ключами и перезагрузки
    permission: frostcases.admin
